### ISSUE TITLE
Some stubs are not converted, maybe due to a "execute N times" call?

### ISSUE THREAD

**Issue by sbleon** [jaredbeck/minitest_to_rspec#11]
In: `Password.any_instance.stubs(:destroy).once`

Out (expected): `expect_any_instance_of(Password).to receive(:destroy).once`

Out (actual): `Password.any_instance.stubs(:destroy).once`

I guess without the `.once` in the input, I would expect the output to be an `allow_any_instance_of`, but the `.once` makes it more of an expectation than just a stub.

**Comment by jaredbeck** [comment]
> I guess without the .once in the input, I would expect the output to be an allow_any_instance_of, but the .once makes it more of an expectation than just a stub.

The documentation for `stubs` says it ..

> Adds an expectation that the specified method may be called any number of times with any parameters.

So, `any_instance.stubs` should always be converted to `expect_any_instance_of`, AFAICT.

**Comment by jaredbeck** [comment]
On second thought, the following are not equivalent:

```
x.stubs(:y) # Expects any number of calls, including zero calls
expect(x).to receive(:y) # Expects one or more calls
```

**Comment by jaredbeck** [comment]
Closing via https://github.com/jaredbeck/minitest_to_rspec/pull/15
