### ISSUE TITLE
mishandles nested `masgn` nodes in block args

### ISSUE THREAD

**Issue by jaynetics** [jaredbeck/minitest_to_rspec#24]
a.k.a. parenthesized block arguments.

this might be a bug in [`ruby_parser`](https://github.com/seattlerb/ruby_parser) or [`ruby2ruby`](https://github.com/seattlerb/ruby2ruby).

example:

```ruby
test("ok") { foo { |(bar, (baz, qux)), ugh| agh } }
```

output
```ruby
it("ok") { foo { |(bar, masgn, baz, qux), ugh| agh } }
```

**Comment by jaredbeck** [comment]
> this might be a bug in ruby_parser or ruby2ruby.

Those projects are very well tested so it's more likely a bug in `minitest_to_rspec` :)

**Comment by janosch-x** [comment]
doesn't seem so - https://github.com/seattlerb/ruby2ruby/issues/50

**Comment by jaredbeck** [comment]
Thanks Janosch, Given https://github.com/seattlerb/ruby2ruby/issues/50, should we close this, or is there more to do here?

**Comment by jaynetics** [comment]
@jaredbeck that depends on whether you want to leave this open as a warning / heads-up or not.

the bug is still there because the fix wasn't merged into ruby2ruby.

in the minitest codebase where i encountered a lot of these, i ended up working around it by using my branch of ruby2ruby.

on the other hand it is probably a rare issue.

**Comment by jaredbeck** [comment]
I think we can close this? According to https://github.com/seattlerb/ruby2ruby/issues/50#issuecomment-478908839 it's fixed?
